### ISSUE TITLE
Programmer doesn't recognize common Internet protocols

### ISSUE THREAD

**Issue by TvdW** [AlicanC/AlicanC-s-Modern-Warfare-2-Tool#1]
https://github.com/AlicanC/AlicanC-s-Modern-Warfare-2-Tool/blob/master/ACMW2HostTool/MW2Packets.cs

You might like to know that you were parsing IPv4 and UDP packets. Look them up on Wikipedia, then laugh at your description of the fields :-)

**Comment by AlicanC** [comment]
I had no idea and had to reverse them with my close-to-zero knowledge of those stuff. I always knew I was doing something wrong :D
